/* Generated By:JavaCC: Do not edit this line. wcConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface wcConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tPALABRA = 1;
  /** RegularExpression Id. */
  int tNL = 2;
  /** RegularExpression Id. */
  int tTAB = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<tPALABRA>",
    "\"\\n\"",
    "\"\\t\"",
  };

}
