/* alikeTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. alikeTokenManager.java */
package traductor;

/** Token Manager. */
public class alikeTokenManager implements alikeConstants {
        static void CommonTokenAction(Token token) {
                if (token.kind == tRESTO) System.out.println("ERROR LEXICO: (" + token.beginLine + ", " + token.beginColumn + "): simbolo no reconocido: " + token.image);
                System.out.println("(" + token.beginLine + ", " + token.beginColumn + "): " + alikeConstants.tokenImage[token.kind] + " " + token.image);
        }

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_1(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x37fc08001ff600L) != 0L)
         {
            jjmatchedKind = 54;
            return 23;
         }
         if ((active0 & 0x4000000L) != 0L)
            return 0;
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            return 11;
         }
         return -1;
      case 1:
         if ((active0 & 0x3efc08001f9600L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 1;
            return 23;
         }
         if ((active0 & 0x1000000006000L) != 0L)
            return 23;
         return -1;
      case 2:
         if ((active0 & 0x380800001400L) != 0L)
            return 23;
         if ((active0 & 0x3ec400001f8200L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 54;
               jjmatchedPos = 2;
            }
            return 23;
         }
         return -1;
      case 3:
         if ((active0 & 0x2a000000010000L) != 0L)
            return 23;
         if ((active0 & 0x14d400001e8200L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 3;
            return 23;
         }
         return -1;
      case 4:
         if ((active0 & 0xd400001e8000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 4;
            return 23;
         }
         if ((active0 & 0x14000000000200L) != 0L)
            return 23;
         return -1;
      case 5:
         if ((active0 & 0x20000L) != 0L)
            return 23;
         if ((active0 & 0xd400001c8000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 5;
            return 23;
         }
         return -1;
      case 6:
         if ((active0 & 0x180000L) != 0L)
            return 23;
         if ((active0 & 0xd40000048000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 6;
            return 23;
         }
         return -1;
      case 7:
         if ((active0 & 0x40000048000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 7;
            return 23;
         }
         if ((active0 & 0xd00000000000L) != 0L)
            return 23;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_1(int pos, long active0){
   return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 36);
      case 41:
         return jjStopAtPos(0, 37);
      case 42:
         return jjStopAtPos(0, 27);
      case 43:
         return jjStopAtPos(0, 25);
      case 44:
         return jjStopAtPos(0, 40);
      case 45:
         return jjStartNfaWithStates_1(0, 26, 0);
      case 46:
         return jjMoveStringLiteralDfa1_1(0x20000000000L);
      case 47:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_1(0x100000000L);
      case 58:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_1(0x800L);
      case 59:
         return jjStopAtPos(0, 38);
      case 60:
         jjmatchedKind = 29;
         return jjMoveStringLiteralDfa1_1(0x200000000L);
      case 61:
         return jjStopAtPos(0, 31);
      case 62:
         jjmatchedKind = 30;
         return jjMoveStringLiteralDfa1_1(0x400000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_1(0x80200L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_1(0x800000040000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_1(0x6000000000400L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_1(0x80000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_1(0x1400000102000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_1(0x20000000000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_1(0x800000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_1(0x10000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_1(0x4000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_1(0x300000008000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_1(0x21000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_1(0x40000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_1(0x8000000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_1(0x10000000000000L);
      default :
         return jjMoveNfa_1(3, 0);
   }
}
static private int jjMoveStringLiteralDfa1_1(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         break;
      case 61:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 34);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_1(active0, 0x80000021200L);
      case 70:
      case 102:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_1(1, 14, 23);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_1(1, 48, 23);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_1(active0, 0x18800000040000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa2_1(active0, 0x40000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_1(active0, 0x6000000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_1(active0, 0x400000100400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_1(active0, 0x20000800080000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_1(active0, 0x8000L);
      case 83:
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_1(1, 13, 23);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_1(active0, 0x300000010000L);
      default :
         break;
   }
   return jjStartNfa_1(0, active0);
}
static private int jjMoveStringLiteralDfa2_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_1(active0, 0x800000040000L);
      case 68:
      case 100:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_1(2, 10, 23);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_1(2, 35, 23);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_1(active0, 0x8000000000000L);
      case 70:
      case 102:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_1(2, 12, 23);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_1(active0, 0x200L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_1(active0, 0x10040000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_1(active0, 0x10000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_1(active0, 0x20000000088000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_1(active0, 0x6000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_1(2, 43, 23);
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_1(active0, 0x500000120000L);
      default :
         break;
   }
   return jjStartNfa_1(1, active0);
}
static private int jjMoveStringLiteralDfa3_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 50:
         return jjMoveStringLiteralDfa4_1(active0, 0x400000000000L);
      case 95:
         return jjMoveStringLiteralDfa4_1(active0, 0x100000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_1(active0, 0x8000L);
      case 69:
      case 101:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_1(3, 49, 23);
         return jjMoveStringLiteralDfa4_1(active0, 0x100000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_1(active0, 0x4000000000200L);
      case 76:
      case 108:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_1(3, 16, 23);
         return jjMoveStringLiteralDfa4_1(active0, 0x10000000080000L);
      case 78:
      case 110:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_1(3, 51, 23);
         break;
      case 80:
      case 112:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_1(3, 53, 23);
         return jjMoveStringLiteralDfa4_1(active0, 0x40000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_1(active0, 0x800000040000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_1(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_1(2, active0);
}
static private int jjMoveStringLiteralDfa4_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 50:
         return jjMoveStringLiteralDfa5_1(active0, 0x800000000000L);
      case 95:
         return jjMoveStringLiteralDfa5_1(active0, 0x40000000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_1(active0, 0x40000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_1(active0, 0x400000000000L);
      case 69:
      case 101:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_1(4, 52, 23);
         return jjMoveStringLiteralDfa5_1(active0, 0x88000L);
      case 70:
      case 102:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_1(4, 50, 23);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_1(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_1(active0, 0x100000000000L);
      case 78:
      case 110:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_1(4, 9, 23);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_1(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_1(3, active0);
}
static private int jjMoveStringLiteralDfa5_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_1(active0, 0x80000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_1(active0, 0x40000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_1(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_1(active0, 0x100000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa6_1(active0, 0x400000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_1(active0, 0x900000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_1(active0, 0x40000000000L);
      case 78:
      case 110:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_1(5, 17, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_1(4, active0);
}
static private int jjMoveStringLiteralDfa6_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_1(active0, 0x400000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_1(active0, 0x40000000000L);
      case 78:
      case 110:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_1(6, 19, 23);
         return jjMoveStringLiteralDfa7_1(active0, 0x900000000000L);
      case 82:
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_1(6, 20, 23);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_1(active0, 0x40000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_1(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_1(5, active0);
}
static private int jjMoveStringLiteralDfa7_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_1(7, 44, 23);
         return jjMoveStringLiteralDfa8_1(active0, 0x40000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_1(active0, 0x40000000000L);
      case 82:
      case 114:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_1(7, 46, 23);
         return jjMoveStringLiteralDfa8_1(active0, 0x8000L);
      case 84:
      case 116:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_1(7, 47, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_1(6, active0);
}
static private int jjMoveStringLiteralDfa8_1(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_1(8, 15, 23);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_1(8, 42, 23);
         break;
      case 82:
      case 114:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_1(8, 18, 23);
         break;
      default :
         break;
   }
   return jjStartNfa_1(7, active0);
}
static private int jjStartNfaWithStates_1(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_1(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 24;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  { jjCheckNAdd(23); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     { jjCheckNAdd(8); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     { jjCheckNAdd(8); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  else if (curChar == 45)
                     { jjCheckNAdd(8); }
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 5;
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 10)
                     kind = 2;
                  break;
               case 4:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if (curChar == 39 && kind > 21)
                     kind = 21;
                  break;
               case 7:
                  if (curChar == 45)
                     { jjCheckNAdd(8); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  { jjCheckNAdd(8); }
                  break;
               case 17:
               case 19:
                  if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 18:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 20:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 34 && kind > 24)
                     kind = 24;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     { jjCheckNAdd(23); }
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     { jjCheckNAdd(23); }
                  }
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 1:
                  { jjAddStates(3, 4); }
                  break;
               case 5:
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if ((0x2000000020L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 10:
                  if ((0x20000000200000L & l) != 0L)
                     { jjCheckNAdd(9); }
                  break;
               case 12:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if ((0x8000000080000L & l) != 0L)
                     { jjCheckNAdd(9); }
                  break;
               case 14:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  { jjAddStates(0, 2); }
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  { jjCheckNAdd(23); }
                  break;
               case 23:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  { jjCheckNAdd(23); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(3, 4); }
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 18:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 24 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 1);
      default :
         return 1;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, "\72\75", null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\53", 
"\55", "\52", "\57", "\74", "\76", "\75", "\57\75", "\74\75", "\76\75", null, "\50", 
"\51", "\73", "\72", "\54", "\56\56", null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   18, 20, 21, 1, 2, 
};

static int curLexState = 1;
static int defaultLexState = 1;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      CommonTokenAction(matchedToken);
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 55)
       {
          jjmatchedKind = 55;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           CommonTokenAction(matchedToken);
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 24 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // quitamos la doble "" por "
        matchedToken.image = image.toString().replaceAll("\"\"", "\"");
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public alikeTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public alikeTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 24; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "COMILLAS",
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffe01L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[24];
    static private final int[] jjstateSet = new int[2 * 24];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
