/* Generated By:JavaCC: Do not edit this line. alikeConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface alikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCOMMENT = 2;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int tBEGIN = 9;
  /** RegularExpression Id. */
  int tEND = 10;
  /** RegularExpression Id. */
  int tASIGN = 11;
  /** RegularExpression Id. */
  int tREF = 12;
  /** RegularExpression Id. */
  int tIS = 13;
  /** RegularExpression Id. */
  int tOF = 14;
  /** RegularExpression Id. */
  int tPROC = 15;
  /** RegularExpression Id. */
  int tFUNC = 16;
  /** RegularExpression Id. */
  int tNULL = 17;
  /** RegularExpression Id. */
  int tARRAY = 18;
  /** RegularExpression Id. */
  int tRETURN = 19;
  /** RegularExpression Id. */
  int tEXIT = 20;
  /** RegularExpression Id. */
  int tCHAR = 21;
  /** RegularExpression Id. */
  int tBOOL = 22;
  /** RegularExpression Id. */
  int tINT = 23;
  /** RegularExpression Id. */
  int tCHARCONST = 24;
  /** RegularExpression Id. */
  int tINTCONST = 25;
  /** RegularExpression Id. */
  int tTRUE = 26;
  /** RegularExpression Id. */
  int tFALSE = 27;
  /** RegularExpression Id. */
  int tSTRING = 28;
  /** RegularExpression Id. */
  int tAND = 29;
  /** RegularExpression Id. */
  int tOR = 30;
  /** RegularExpression Id. */
  int tNOT = 31;
  /** RegularExpression Id. */
  int tPLUS = 32;
  /** RegularExpression Id. */
  int tMINUS = 33;
  /** RegularExpression Id. */
  int tTIMES = 34;
  /** RegularExpression Id. */
  int tDIV = 35;
  /** RegularExpression Id. */
  int tLT = 36;
  /** RegularExpression Id. */
  int tGT = 37;
  /** RegularExpression Id. */
  int tEQ = 38;
  /** RegularExpression Id. */
  int tNE = 39;
  /** RegularExpression Id. */
  int tLE = 40;
  /** RegularExpression Id. */
  int tGE = 41;
  /** RegularExpression Id. */
  int tMOD = 42;
  /** RegularExpression Id. */
  int tAPAR = 43;
  /** RegularExpression Id. */
  int tCPAR = 44;
  /** RegularExpression Id. */
  int tPC = 45;
  /** RegularExpression Id. */
  int tDP = 46;
  /** RegularExpression Id. */
  int tCOMA = 47;
  /** RegularExpression Id. */
  int tRANGE = 48;
  /** RegularExpression Id. */
  int tSKIPLINE = 49;
  /** RegularExpression Id. */
  int tGET = 50;
  /** RegularExpression Id. */
  int tPUTLINE = 51;
  /** RegularExpression Id. */
  int tPUT = 52;
  /** RegularExpression Id. */
  int tINT2CHAR = 53;
  /** RegularExpression Id. */
  int tCHAR2INT = 54;
  /** RegularExpression Id. */
  int tIF = 55;
  /** RegularExpression Id. */
  int tELSE = 56;
  /** RegularExpression Id. */
  int tELSIF = 57;
  /** RegularExpression Id. */
  int tTHEN = 58;
  /** RegularExpression Id. */
  int tWHILE = 59;
  /** RegularExpression Id. */
  int tLOOP = 60;
  /** RegularExpression Id. */
  int tID = 61;
  /** RegularExpression Id. */
  int tRESTO = 62;

  /** Lexical state. */
  int COMILLAS = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "<tCOMMENT>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<LETTER>",
    "<DIGIT>",
    "\"begin\"",
    "\"end\"",
    "\":=\"",
    "\"ref\"",
    "\"is\"",
    "\"of\"",
    "\"procedure\"",
    "\"function\"",
    "\"null\"",
    "\"array\"",
    "\"return\"",
    "\"exit\"",
    "\"character\"",
    "\"boolean\"",
    "\"integer\"",
    "<tCHARCONST>",
    "<tINTCONST>",
    "\"true\"",
    "\"false\"",
    "<tSTRING>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"/=\"",
    "\"<=\"",
    "\">=\"",
    "\"mod\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"..\"",
    "\"skip_line\"",
    "\"get\"",
    "\"put_line\"",
    "\"put\"",
    "\"int2char\"",
    "\"char2int\"",
    "\"if\"",
    "\"else\"",
    "\"elsif\"",
    "\"then\"",
    "\"while\"",
    "\"loop\"",
    "<tID>",
    "<tRESTO>",
    "\"\"",
  };

}
